"""Add exchange_rate to invoices

Revision ID: 3fbe72285c56
Revises: 25954c0c9972
Create Date: 2025-12-25 13:15:56.461330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbe72285c56'
down_revision = '25954c0c9972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')

    # ### end Alembic commands ###
